GET http://localhost:80/meanapps

###

DELETE http://localhost:80/meanapps/5e3c8697e7179a2f0119354a
Content-Type: application/json

{
  "logo": "https://res.cloudinary.com/hazicy5aw/image/upload/c_scale,h_200/v1581181852/logo-MV_qlhdbe.png",
  "url": "https://ma-vitesse.app"
}

###

POST http://localhost:80/meanapps
Content-Type: application/json

{
  "name": "MA Vitesse Live",
  "description": "GPS avec vitesse, distance et durée en temps réel.",
  "logo": "https://res.cloudinary.com/hazicy5aw/image/upload/c_scale,h_200/v1583056724/logo-MVL_w0bqbu.png",
  "url": "https://live.ma-vitesse.app",
  "colors": {
    "primary": "#22333B",
    "secondary": "#C83636"
  }
}

###

PATCH http://localhost:80/meanapps/5e3ef0a29328920be2c9a827
Content-Type: application/json

{
  "logo": "https://res.cloudinary.com/hazicy5aw/image/upload/c_scale,h_200/v1581181852/logo-MV_qlhdbe.png",
  "url": "https://ma-vitesse.app"
}

###

GET http://localhost:80/featuresuggests

###

DELETE http://localhost:80/featuresuggests/5e3fe226fed57f0626d0c89f

###

POST http://localhost:80/featuresuggests
Content-Type: application/json

{
  "description": "Ajout d'un mode nuit",
  "contributor_email": "arthur.briere@gmail.com"
}

###

PATCH http://localhost:80/featuresuggests/5e3fe226fed57f0626d0c89f
Content-Type: application/json

{
  "contributor_email": "jeanlouislarun@gmail.com"
}

###